[모휘정] 숙소 리스트 뷰 추가
wecode-bootcamp-korea/29-2nd-MyJejuStay-backend pull request #11
Opened 2022-02-19 13:46 UTC by walkersmind

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 숙소 목록을 출력하는 View 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 숙소 이름, 이미지, 설명 등을 담은 리스트를 출력
- 필터링 기능 제공 (테마, 예약 가능 인원, 지역 등)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- Q 필터링 사용에 대해 다시 한번 더 학습할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항

2022-02-21 02:34 UTC, bigfanoftim requested changes
view와 modeling 수정사항은 서로 다른 PR로 작성해주세요!

2022-02-21 07:24 UTC, bigfanoftim requested changes
휘정님 뷰 추가 PR에 왜 migrations 파일들이 올라와 있을까요?ㅠㅠ 완벽히 분리하고 마이그레이션 수정 필요한 부분 있으면 따로 PR올리셔서 머지받으신 후에 창현님께도 공유해주세요.

그리고 우선 전체적인 코드 큰 문제 없으니 컨벤션만 다시 맞춰서 푸시해주세요~

2022-02-21 08:09 UTC, walkersmind commented
> 휘정님 뷰 추가 PR에 왜 migrations 파일들이 올라와 있을까요?ㅠㅠ 완벽히 분리하고 마이그레이션 수정 필요한 부분 있으면 따로 PR올리셔서 머지받으신 후에 창현님께도 공유해주세요.
> 
> 그리고 우선 전체적인 코드 큰 문제 없으니 컨벤션만 다시 맞춰서 푸시해주세요~

호준님 안녕하세요! 마이그레이션 파일 또한 모델링 브랜치에서 작업하고 와야 하는 것이군요. 동일한 피드백을 계속 드리게 해서 죄송합니다. 말씀해주신 부분 수정해서 다시 올리도록 하겠습니다..!

2022-02-22 05:38 UTC, bigfanoftim approved these changes

2022-02-22 05:39 UTC, merged