[최창현] front와 통신완료
wecode-bootcamp-korea/29-2nd-MyJejuStay-backend pull request #13
Opened 2022-02-21 07:11 UTC by cch0807

test케이스 작성 완료

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 카카오 소셜 로그인

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1. 프론트에서 카카오 토큰을 넘겨받음

2. 카카오에 토큰 유효성 확인 후 유저 정보 받아오기

3. 유저정보를 바탕으로 jwt토큰을 발행하여 프론트에게 전달하기

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
소셜 로그인의 흐름을 알게되었습니다!
<br />

## :: 기타 질문 및 특이 사항

- 테스트 케이스 작성이 올바르게 된건지 궁금합니다!

2022-02-21 07:26 UTC, bigfanoftim commented
PR 제목 정확히 남겨주세요 창현님

2022-02-21 07:28 UTC, bigfanoftim requested changes
불필요한 코드들 삭제 후 다시 푸시해주세요~

2022-02-21 07:28 UTC, bigfanoftim commented on users/views.py
> +      print(kakao_id)
불필요한 print문 지워주세요!
```suggestion
```

2022-02-21 08:14 UTC, cch0807 commented on users/views.py
> +      print(kakao_id)
수정했습니다!

2022-02-22 05:59 UTC, bigfanoftim approved these changes

2022-02-22 06:06 UTC, merged