[최창현] Mainpage Video Url
wecode-bootcamp-korea/29-2nd-MyJejuStay-backend pull request #14
Opened 2022-02-21 08:41 UTC by cch0807

엔드포인트 이름 변경
branch이름 변경
view이름 변경

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

메인페이지에 s3 버킷에 올린 영상 url 반환

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

s3 버킷 구현
버킷에 메인페이지에 랜더링할 영상 업로드
엔드포인트 이름 변경
branch이름 변경
view이름 변경
view 수정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

aws s3에 대해서 학습하였습니다!

2022-02-22 08:55 UTC, bigfanoftim requested changes

2022-02-22 08:55 UTC, bigfanoftim commented on myjejustay/urls.py
> +  path('', include('mainpages.urls')),
엔드포인트 주소를 공백으로 하신 이유가 있을까요? 보다 정확한 값을 적어주는게 좋을 것 같아요. 

만약 홈페이지에서 도메인 뒤 아무 값도 붙여주지 않기 때문에 이런 방식으로 처리 하셨다면 그건 약간의 오해가 있어서 그런 것 같습니다.
- 우선 api를 호출하는 주소는 유저가 보는 도메인과는 상관이 없고 오로지 프론트엔드에서 요청을 보내는 주소일 뿐입니다.
- 따라서 오로지 해당 api가 다루는 데이터를 메인으로 생각하고 엔드포인트 주소를 작성해주시면 됩니다.

2022-02-22 08:55 UTC, bigfanoftim commented on mainpages/urls.py
> +  path('mainpagevideo ', PageVideoView.as_view())
항상 데이터 중심으로 엔드포인트 주소를 작성하는 법을 익혀야 합니다!
```python
# 전체 비디오를 불러올 때
:8000/videos

# 해당 id를 가진 비디오만 불러올 때
:8000/video/1
```

2022-02-23 05:10 UTC, cch0807 commented on myjejustay/urls.py
> +  path('', include('mainpages.urls')),
확인 했습니다!!

2022-02-23 05:10 UTC, cch0807 commented on mainpages/urls.py
> +  path('mainpagevideo ', PageVideoView.as_view())
확인했습니다!!

2022-02-23 05:37 UTC, bigfanoftim requested changes

2022-02-23 05:37 UTC, bigfanoftim commented on mainpages/views.py
> +      video_url = MainPageVideo.objects.get(id=video_id).video_url
불필요한 print문 삭제해주세요!
```suggestion
      video_id = request.GET.get('video_id', 1)
      video_url = MainPageVideo.objects.get(id=video_id).video_url
```

2022-02-23 05:58 UTC, cch0807 commented on mainpages/views.py
> +      video_url = MainPageVideo.objects.get(id=video_id).video_url
삭제했습니다!

2022-02-23 06:26 UTC, bigfanoftim approved these changes
LGTM 👍

2022-02-23 06:26 UTC, merged