[ADD] login view (login_decorator 추가)
wecode-bootcamp-korea/29-2nd-MyJejuStay-backend pull request #15
Opened 2022-02-21 11:36 UTC by cch0807

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

일반 이메일 로그인

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

1.  bcrypt를 통해 password 검사
2. 검사 성공 시 jwt토큰 발급
3. login decorator구현

2022-02-22 08:56 UTC, bigfanoftim requested changes

2022-02-22 08:56 UTC, bigfanoftim commented on users/views.py
> +
`get` method를 사용할 때 일어날 수 있는 에러에 대한 예외처리만 추가해주세요!

2022-02-23 05:08 UTC, cch0807 commented on users/views.py
> +
확인했습니다 호준님 ^ㅁ ^

2022-02-23 05:38 UTC, bigfanoftim approved these changes

2022-02-23 05:38 UTC, merged