[모휘정] 숙소 뷰 리팩토링: 코드 리뷰 반영
wecode-bootcamp-korea/29-2nd-MyJejuStay-backend pull request #17
Opened 2022-02-23 05:24 UTC by walkersmind

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- 숙소 뷰 개선

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- 뷰 로직 개선
- 코드 리뷰 반영

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 프론트에 단순히 데이터를 주는 것이 아니라, 해당 데이터를 백엔드에서 효율적이고 정확하게 관리하는 것의 중요성에 대해 인식할 수 있었습니다.

<br />

## :: 기타 질문 및 특이 사항

- 피드백 주신 예약 부분은 `datetime`에 `range`가 생각대로 적용되지 않아 계속해서 개선해보려고 합니다.

2022-02-23 05:40 UTC, bigfanoftim requested changes
unit test 추가해주세요~

2022-02-23 05:40 UTC, bigfanoftim commented on accommodations/views.py
> +            user_id = 1
하드코딩 지워주세요

2022-02-23 05:40 UTC, bigfanoftim commented on accommodations/views.py
> +                # user_id : need_to_be_added,
PR은 다른기능이 완성되었다고 생각하고 실제 환경에서 동작할 수 있는 코드로 올려주세요 휘정님, 
제대로 완성이 안된 PR이라면 라벨을 올바르게 달아주세요

2022-02-23 22:58 UTC, walkersmind commented on accommodations/views.py
> +            user_id = 1
호준님 안녕하세요. `user_id=1` 로 된 부분은 어제 말씀드린 오류가 있어서 로그인 통신 재확인 후 다시 수정하려고 합니다.

2022-02-24 13:52 UTC, bigfanoftim approved these changes

2022-02-24 13:52 UTC, merged